[package]
name = "fluid_sim"
version = "0.1.0"
authors = ["Hannes Ojala <hannesojala123@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.14"
[dependencies.sdl2]
version = "0.34"
